module.exports = {
  en: {
    notes_title: "Notes",
    footer_based: "Based in Cologne, Germany",
    footer_navigate: "Navigate",
    footer_follow: "Follow",
    view: "View",
    search_placeholder: "Search concerts…",
    no_results: "No concerts found.",
    previous: "Previous",
    next: "Next",
    dir: '',
    site_title: 'Veronique De Raedemaeker',
    site_subtitle: 'Violinist',
    biography: 'Read the full biography',
    highlights_title: 'Highlights',
    most_recent_highlight: 'Latest Highlight',
    see_all_highlights: 'See all highlights',
    upcoming_concerts: 'Upcoming Concerts',
    no_highlights: 'No highlights found.',
    see_all_concerts: 'All Concerts Overview',
    no_upcoming: 'No upcoming concerts at this time.',
    back_to_overview: 'Back to overview',
    archive: 'Archive',
    concerts_title: 'Concerts',
    projects_title: 'Projects',
    contact_title: 'Contact',
    send_message: 'Send a Message',
    your_name: 'Your name',
    your_email: 'Your email address',
    message: 'Message',
    send_button: 'Send',
    newsletter: 'Newsletter',
    copyright: 'All rights reserved.',
    tickets: 'Tickets & Info',
    full_page: 'Full page',
    success_title: 'Thank you',
    success_message: 'Your message has been received.',
    back_home: 'Back to home',
    details: "Details",
    show_earlier: "Show earlier concerts",
    contact_intro: "For bookings, programmes, press, or anything else — write a message below.",
    subscribe: "Subscribe",
    share: "Share",
    add_to_calendar: "Add to calendar",
    print: "Print",
    link_copied: "Link copied",
    newsletter_hint: "Stay up to date with the latest concerts, recordings and highlights.",
    no_projects: "No projects found."
  },
  nl: {
    notes_title: "Notities",
    footer_based: "Gevestigd in Keulen, Duitsland",
    footer_navigate: "Navigatie",
    footer_follow: "Volg",
    view: "Bekijk",
    search_placeholder: "Zoek concerten…",
    no_results: "Geen concerten gevonden.",
    previous: "Vorige",
    next: "Volgende",
    dir: '',
    site_title: 'Veronique De Raedemaeker',
    site_subtitle: 'Violiste',
    biography: 'Lees de volledige biografie',
    highlights_title: 'Hoogtepunten',
    most_recent_highlight: 'Laatste Hoogtepunt',
    see_all_highlights: 'Bekijk alle hoogtepunten',
    upcoming_concerts: 'Aankomende Concerten',
    no_highlights: 'Geen hoogtepunten gevonden.',
    see_all_concerts: 'Overzicht alle concerten',
    no_upcoming: 'Momenteel geen aankomende concerten.',
    back_to_overview: 'Terug naar overzicht',
    archive: 'Archief',
    concerts_title: 'Concerten',
    projects_title: 'Projecten',
    contact_title: 'Contact',
    send_message: 'Stuur een bericht',
    your_name: 'Uw naam',
    your_email: 'Uw e-mailadres',
    message: 'Bericht',
    send_button: 'Verzenden',
    newsletter: 'Nieuwsbrief',
    copyright: 'Alle rechten voorbehouden.',
    tickets: 'Tickets & info',
    full_page: 'Volledige pagina',
    success_title: 'Bedankt',
    success_message: 'Uw bericht is goed ontvangen.',
    back_home: 'Terug naar home',
    details: "Details",
    show_earlier: "Eerdere concerten tonen",
    contact_intro: "Voor boekingen, programma’s, pers of iets anders — stuur hieronder een bericht.",
    subscribe: "Inschrijven",
    share: "Delen",
    add_to_calendar: "Zet in agenda",
    print: "Afdrukken",
    link_copied: "Link gekopieerd",
    newsletter_hint: "Blijf op de hoogte van de nieuwste concerten, opnames en hoogtepunten — rechtstreeks van Veronique.",
    no_projects: "Geen projecten gevonden."
  },
  fr: {
    notes_title: "Notes",
    footer_based: "Basée à Cologne, Allemagne",
    footer_navigate: "Navigation",
    footer_follow: "Suivre",
    view: "Voir",
    search_placeholder: "Rechercher des concerts…",
    no_results: "Aucun concert trouvé.",
    previous: "Précédent",
    next: "Suivant",
    dir: '',
    site_title: 'Veronique De Raedemaeker',
    site_subtitle: 'Violoniste',
    biography: 'Lire la biographie complète',
    highlights_title: 'Highlights',
    most_recent_highlight: 'Dernier Highlight',
    see_all_highlights: 'Voir tous les highlights',
    upcoming_concerts: 'Concerts à venir',
    no_highlights: 'Aucun highlight trouvé.',
    see_all_concerts: 'Vue d\'ensemble des concerts',
    no_upcoming: 'Pas de concerts à venir pour le moment.',
    back_to_overview: 'Retour à l\'aperçu',
    archive: 'Archives',
    concerts_title: 'Concerts',
    projects_title: 'Projets',
    contact_title: 'Contact',
    send_message: 'Envoyer un message',
    your_name: 'Votre nom',
    your_email: 'Votre adresse e-mail',
    message: 'Message',
    send_button: 'Envoyer',
    newsletter: 'Newsletter',
    copyright: 'Tous droits réservés.',
    tickets: 'Billets & infos',
    full_page: 'Page complète',
    success_title: 'Merci',
    success_message: 'Votre message a bien été reçu.',
    back_home: 'Retour à l\'accueil',
    details: "Détails",
    show_earlier: "Afficher les concerts précédents",
    contact_intro: "Pour les réservations, programmes, presse ou toute autre demande — écrivez un message ci-dessous.",
    subscribe: "S’abonner",
    share: "Partager",
    add_to_calendar: "Ajouter au calendrier",
    print: "Imprimer",
    link_copied: "Lien copié",
    newsletter_hint: "Restez au courant des derniers concerts, enregistrements et moments forts — directement de Veronique.",
    no_projects: "Aucun projet trouvé."
  },
  de: {
    notes_title: "Notizen",
    footer_based: "Ansässig in Köln, Deutschland",
    footer_navigate: "Navigation",
    footer_follow: "Folgen",
    view: "Ansehen",
    search_placeholder: "Konzerte suchen…",
    no_results: "Keine Konzerte gefunden.",
    previous: "Zurück",
    next: "Weiter",
    dir: '',
    site_title: 'Veronique De Raedemaeker',
    site_subtitle: 'Geigerin',
    biography: 'Die vollständige Biografie lesen',
    highlights_title: 'Highlights',
    most_recent_highlight: 'Neuestes Highlight',
    see_all_highlights: 'Alle Highlights ansehen',
    upcoming_concerts: 'Kommende Konzerte',
    no_highlights: 'Keine Highlights gefunden.',
    see_all_concerts: 'Alle Konzerte im Überblick',
    no_upcoming: 'Derzeit keine kommenden Konzerte.',
    back_to_overview: 'Zurück zur Übersicht',
    archive: 'Archiv',
    concerts_title: 'Konzerte',
    projects_title: 'Projekte',
    contact_title: 'Kontakt',
    send_message: 'Nachricht senden',
    your_name: 'Ihr Name',
    your_email: 'Ihre E-Mail-Adresse',
    message: 'Nachricht',
    send_button: 'Senden',
    newsletter: 'Newsletter',
    copyright: 'Alle Rechte vorbehalten.',
    tickets: 'Tickets & Infos',
    full_page: 'Ganze Seite',
    success_title: 'Danke',
    success_message: 'Ihre Nachricht ist gut angekommen.',
    back_home: 'Zurück zur Startseite',
    details: "Details",
    show_earlier: "Frühere Konzerte anzeigen",
    contact_intro: "Für Buchungen, Programme, Presse oder anderes — schreiben Sie unten eine Nachricht.",
    subscribe: "Abonnieren",
    share: "Teilen",
    add_to_calendar: "In den Kalender",
    print: "Drucken",
    link_copied: "Link kopiert",
    newsletter_hint: "Bleiben Sie auf dem Laufenden über die neuesten Konzerte, Aufnahmen und Highlights — direkt von Veronique.",
    no_projects: "Keine Projekte gefunden.",
  }
};
