module.exports = {
  en: {
    dir: '',
    site_title: 'Veronique De Raedemaeker',
    site_subtitle: 'Violinist',
    availableText: 'This page is also available in:',
    biography: 'Read the full biography',
    concerts: 'All Concerts',
    view_projects: 'View Projects',
    most_recent_highlight: 'Latest Highlight',
    see_all_highlights: 'See all highlights',
    upcoming_concerts: 'Upcoming Concerts',
    no_highlights: 'No highlights found.',
    see_all_concerts: 'All Concerts Overview',
    no_upcoming: 'No upcoming concerts at this time.',
    back_to_overview: 'Back to overview',
    read_more: 'Read more',
    explore: 'Explore',
    search_placeholder: 'Search concerts...',
    search_button: 'Search',
    archive: 'Archive',
    concerts_title: 'Concerts',
    projects_title: 'Projects',
    highlights_title: 'Highlights',
    about_title: 'About',
    contact_title: 'Contact',
    send_message: 'Send a Message',
    your_name: 'Your name',
    your_email: 'Your email address',
    message: 'Message',
    send_button: 'Send',
    newsletter: 'Newsletter',
    find_me: 'Find me on',
    copyright: 'All rights reserved.',
    tickets: 'Tickets & Info',
    full_page: 'Full page',
    success_title: 'Thank you',
    success_message: 'Your message has been received.',
    back_home: 'Back to home',
  },
  nl: {
    dir: '',
    site_title: 'Veronique De Raedemaeker',
    site_subtitle: 'Violiste',
    availableText: 'Deze pagina is ook beschikbaar in het:',
    biography: 'Lees de volledige biografie',
    concerts: 'Alle Concerten',
    view_projects: 'Bekijk Projecten',
    most_recent_highlight: 'Laatste Hoogtepunt',
    see_all_highlights: 'Bekijk alle hoogtepunten',
    upcoming_concerts: 'Aankomende Concerten',
    no_highlights: 'Geen hoogtepunten gevonden.',
    see_all_concerts: 'Overzicht alle concerten',
    no_upcoming: 'Momenteel geen aankomende concerten.',
    back_to_overview: 'Terug naar overzicht',
    read_more: 'Lees meer',
    explore: 'Ontdek',
    search_placeholder: 'Zoek concerten...',
    search_button: 'Zoeken',
    archive: 'Archief',
    concerts_title: 'Concerten',
    projects_title: 'Projecten',
    highlights_title: 'Hoogtepunten',
    about_title: 'Over',
    contact_title: 'Contact',
    send_message: 'Stuur een bericht',
    your_name: 'Uw naam',
    your_email: 'Uw e-mailadres',
    message: 'Bericht',
    send_button: 'Verzenden',
    newsletter: 'Nieuwsbrief',
    find_me: 'Vind me op',
    copyright: 'Alle rechten voorbehouden.',
    tickets: 'Tickets & info',
    full_page: 'Volledige pagina',
    success_title: 'Bedankt',
    success_message: 'Uw bericht is goed ontvangen.',
    back_home: 'Terug naar home',
  },
  fr: {
    dir: '',
    site_title: 'Veronique De Raedemaeker',
    site_subtitle: 'Violoniste',
    availableText: 'Cette page est aussi disponible en:',
    biography: 'Lire la biographie complète',
    concerts: 'Tous les Concerts',
    view_projects: 'Voir les projets',
    most_recent_highlight: 'Dernier Highlight',
    see_all_highlights: 'Voir tous les highlights',
    upcoming_concerts: 'Concerts à venir',
    no_highlights: 'Aucun highlight trouvé.',
    see_all_concerts: 'Vue d\'ensemble des concerts',
    no_upcoming: 'Pas de concerts à venir pour le moment.',
    back_to_overview: 'Retour à l\'aperçu',
    read_more: 'Lire la suite',
    explore: 'Découvrir',
    search_placeholder: 'Rechercher des concerts...',
    search_button: 'Rechercher',
    archive: 'Archives',
    concerts_title: 'Concerts',
    projects_title: 'Projets',
    highlights_title: 'Highlights',
    about_title: 'À propos',
    contact_title: 'Contact',
    send_message: 'Envoyer un message',
    your_name: 'Votre nom',
    your_email: 'Votre adresse e-mail',
    message: 'Message',
    send_button: 'Envoyer',
    newsletter: 'Newsletter',
    find_me: 'Retrouvez-moi sur',
    copyright: 'Tous droits réservés.',
    tickets: 'Billets & infos',
    full_page: 'Page complète',
    success_title: 'Merci',
    success_message: 'Votre message a bien été reçu.',
    back_home: 'Retour à l\'accueil',
  },
  de: {
    dir: '',
    site_title: 'Veronique De Raedemaeker',
    site_subtitle: 'Geigerin',
    availableText: 'Diese Seite ist auch verfügbar auf:',
    biography: 'Die vollständige Biografie lesen',
    concerts: 'Alle Konzerte',
    view_projects: 'Projekte ansehen',
    most_recent_highlight: 'Neuestes Highlight',
    see_all_highlights: 'Alle Highlights ansehen',
    upcoming_concerts: 'Kommende Konzerte',
    no_highlights: 'Keine Highlights gefunden.',
    see_all_concerts: 'Alle Konzerte im Überblick',
    no_upcoming: 'Derzeit keine kommenden Konzerte.',
    back_to_overview: 'Zurück zur Übersicht',
    read_more: 'Weiterlesen',
    explore: 'Entdecken',
    search_placeholder: 'Konzerte suchen...',
    search_button: 'Suchen',
    archive: 'Archiv',
    concerts_title: 'Konzerte',
    projects_title: 'Projekte',
    highlights_title: 'Highlights',
    about_title: 'Über',
    contact_title: 'Kontakt',
    send_message: 'Nachricht senden',
    your_name: 'Ihr Name',
    your_email: 'Ihre E-Mail-Adresse',
    message: 'Nachricht',
    send_button: 'Senden',
    newsletter: 'Newsletter',
    find_me: 'Finden Sie mich auf',
    copyright: 'Alle Rechte vorbehalten.',
    tickets: 'Tickets & Infos',
    full_page: 'Ganze Seite',
    success_title: 'Danke',
    success_message: 'Ihre Nachricht ist gut angekommen.',
    back_home: 'Zurück zur Startseite',
  }
};
